name: Setup

on: [push]

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install XFCE 
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp

    - name: Configure XFCE
      run: |
        echo "xfce4-session" > ~/.xsession
        sudo sed -i 's/3389/3390/g' /etc/xrdp/xrdp.ini
        sudo service xrdp restart

    - name: Set up XFCE user
      run: |
        sudo useradd -m rdpuser -s /bin/bash
        echo 'rdpuser:rdppassword' | sudo chpasswd
        sudo adduser rdpuser sudo

    - name: Print connection details
      run: |
        echo "Connect to the RDP server using the following details:"
        echo "Server IP: $(curl -s ifconfig.me)"
        echo "Port: 3390"
        echo "Username: rdpuser"
        echo "Password: rdppassword"
