name: GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  rdp:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install XFCE 
        run: |
          sudo apt update && sudo apt install -y xfce4 xfce4-goodies xrdp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Create User and Set Password
        run: |
          sudo useradd -m githubrdp
          echo 'githubrdp:password123' | sudo chpasswd
          sudo usermod -aG sudo githubrdp

      - name: Get Public IP
        run: |
          sleep 30
          curl -s ifconfig.me
          echo "Use the above IP to connect via RDP with username 'githubrdp' and password 'password123'."

      - name: Keep Session Alive
        run: |
          while true; do sleep 600; done
