name: SSH with tmate

on: 
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  ssh-session:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up tmate session
      run: |
        sudo apt-get update
        sudo apt-get install -y tmate
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
        tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
    - name: Keep tmate session alive
      run: |
        while true; do sleep 1; done
